export const ARTIST_INPUT_FIELD_CHARACTER_LIMIT_FORMATTED = 100;
export const CHANNEL_NAME_INPUT_FIELD_CHARACTER_LIMIT = 30;
export const FEATURES_INPUT_FIELD_CHARACTER_LIMIT = 30;
export const ARTIST_INPUT_FIELD_CHARACTER_LIMIT = 30;
export const TITLE_INPUT_FIELD_CHARACTER_LIMIT = 30;
