export const error = {
  message: {
    characterLimitExceeded: "Character limit exceeded.",
    provideAllRequiredFields: "Please provide all the required fields.",
    removeCommasFromTitle: "Please remove any commas , from the title or artist.",
    somethingWentWrong: "Something went wrong.",
    provideTitle: "Please provide the title.",
    provideArtist: "Please provide the artist.",
    nothingToClear: "There's nothing to clear.",
    provideAValidGenre: "Please provide a valid genre.",
    generateTagsFirst: "Please generate the tags first.",
    removeSpecialCharactersAndNumbersExceptCommasVerse: "Please remove any numbers or special characters.",
    threeVersesAreOnlyAllowed: "You can only include 3 verses.",
    generateTagsBeforeYouCopyToClipboard: "Please generate the tags before you copy to clipboard.",
    artistAndTitleAlreadyProvidedInTheArtistField: "The artist and title was already provided in the artist field.",
    tagsAlreadyRemoved: "Recommended tags have already been removed.",
    needToProvideAllValidVariables: "You need to provide the valid variables.",
    providedVariablesNotValid: "The provided variable is not valid.",
    somethingWentWrongRetrievingCustomFormatKey: "Something went wrong retrieving the custom format key.",
    youHaveAlreadyGeneratedTheExampleResponse: "You've already generated the example response.",
    enterValidKey: "Please enter a valid key.",
    invalidFormat: "Invalid format.",
    methodNotAllowed: "Method Not Allowed",
  },
};
