export const GENRE = {
  alternative: "alternative",
  electronic: "electronic",
  country: "country",
  italian: "italian",
  hiphop: "hiphop",
  dance: "dance",
  phonk: "phonk",
  latin: "latin",
  funk: "funk",
  none: "none",
  rock: "rock",
  trap: "trap",
  pop: "pop",
  rap: "rap",
  edm: "edm",
  emo: "emo",
};
